driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: "test/fixtures/data_bags"

# currently only support 2 last major revs of distros (at the most)
platforms:
  - name: debian-8.6
  - name: debian-7.11
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.3
  - name: centos-6.8
  - name: fedora-25
  - name: fedora-24
  - name: freebsd-11.0
  - name: freebsd-10.3
  - name: opensuse-leap-42.2

suites:
  - name: server
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[openvpn::server]
      - recipe[openvpn::users]
    attributes:
      openvpn:
        config:
          verb: 1
          mute: 10
          route:
           - '192.168.4.0 255.255.255.0'
        push_routes:
          - 192.168.10.0 255.255.255.0
          - 10.12.10.0 255.255.255.0
        push_options:
          dhcp-option:
          - 'DOMAIN local'
          - 'DOMAIN-SEARCH local'
  - name: server_verification
    run_list:
      - recipe[openvpn::server]
      - recipe[openvpn::users]
    attributes:
      openvpn:
        server_verification: "remote-cert-tls server"
    includes: ubuntu-16.04
