driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] || 'latest' %>
  data_bags_path: "test/fixtures/data_bags"

verifier:
  name: inspec

# currently only support 2 last major revs of distros (at the most)
platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-7.3
  - name: debian-8.9
  - name: debian-9.0
  - name: fedora-24
  - name: fedora-25
  - name: freebsd-10.3
  - name: freebsd-11.0
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: server
    run_list:
      - recipe[openvpn::server]
    attributes:
      openvpn:
        config:
          verb: 1
          mute: 10
          route:
           - '192.168.4.0 255.255.255.0'
        push_routes:
          - 192.168.10.0 255.255.255.0
          - 10.12.10.0 255.255.255.0
        push_options:
          dhcp-option:
          - 'DOMAIN local'
          - 'DOMAIN-SEARCH local'
  - name: server_verification
    run_list:
      - recipe[openvpn::server]
      - recipe[openvpn::users]
    attributes:
      openvpn:
        server_verification: "remote-cert-tls server"
    includes: ubuntu-16.04
