---
driver_plugin: vagrant

platforms:
- name: centos-5.8
- name: centos-6.4
- name: ubuntu-1004
  run_list:
  - recipe[apt]
- name: ubuntu-1204
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[openvpn::default]
