---
driver:
  name: dokken
  privileged: true  # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] || 'latest' %>

provisioner:
  name: dokken

verifier:
  name: inspec
  deprecations_as_errors: true

# currently only support 2 last major revs of distros (at the most)
platforms:
  - name: debian-8
    driver:
      image: dokken/debian-8
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update

  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update

  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd

  - name: fedora-latest
    driver:
      image: dokken/fedora-latest
      pid_one_command: /usr/lib/systemd/systemd

  - name: ubuntu-14.04
    driver:
      image: dokken/ubuntu-14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update

  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update

  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update

suites:
  - name: server
    run_list:
      - recipe[openvpn::server]
    attributes:
      openvpn:
        config:
          verb: 1
          mute: 10
          route:
            - '192.168.4.0 255.255.255.0'
        push_routes:
          - 192.168.10.0 255.255.255.0
          - 10.12.10.0 255.255.255.0
        push_options:
          dhcp-option:
            - 'DOMAIN local'
            - 'DOMAIN-SEARCH local'
  - name: server_verification
    run_list:
      - recipe[openvpn::server]
      - recipe[openvpn::users]
    attributes:
      openvpn:
        server_verification: "remote-cert-tls server"
    includes: ubuntu-16.04
  - name: server_verify_no_databag
    run_list:
      - recipe[openvpn::server]
      - recipe[openvpn::users]
    attributes:
      openvpn:
        server_verification: "remote-cert-tls server"
        use_databag: false
    includes: ubuntu-16.04
